### ISSUE TITLE
Fork of the game, new package?

### ISSUE THREAD

**Issue by petitlapin** [flathub/net.sourceforge.Ri-li#7]
Hi,

I've forked the game (to use SDL2 and clean up/modernize the code among other things) and someone asked if I could do a Flatpak package (https://github.com/petitlapin/Li-Ri/issues/33).

I've renamed it as I didn't manage to get in touch with the previous author (the game was done between 2006 and 2007, abandoned since): https://github.com/petitlapin/Li-Ri

Would it make sense to reuse this package to package it or should I do a new one? Would there be a way to redirect this one to the other one or deprecate this one and link to the new one?

Cheers,

Johnny

**Comment by bbhtt** [comment]
Yes it should be a new one with a new app id.
